services:
  fritz:
    restart: unless-stopped
    build: .
    volumes:
      - ./config:/fritz/config
      - ./plugins:/plugins
      - ./cache:/fritz/cache
      - ./logs:/fritz/logs
      - ./ptk:/ptk
